import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
    providedIn: 'root'
})
export class SystemService {

    public jobNames = [
        'Accounting',
        'Administration',
        'Anlageführer',
        'Anlagen- und Apparatebauer',
        'Anlagenführer',
        'Anwendungstechniker',
        'Assistentin Projektleitung',
        'Automatiker',
        'Automobilfachmann/ -Mechatroniker oder -Diagnostiker',
        'Bankschreiner',
        'Bauzeichner',
        'Berater Treuhand',
        'Betriebselektriker',
        'Betriebsmechaniker',
        'Blech-Schweisser',
        'CNC-Dreher',
        'Chemiker',
        'Corporate Response Liaison',
        'Disponent',
        'Dreher',
        'Einbaumaschinist',
        'Elektriker',
        'Elektromonteur',
        'Fachperson Betreuung',
        'Fachperson Gesundheit',
        'Fachperson Qualitätskontrolle',
        'Fenster-/Servicemonteur',
        'Florist',
        'Forward Integration Consultant',
        'HLKKS-Planer',
        'HR Fachperson',
        'HR-Generalistin',
        'Head of Customer Care Service',
        'Head of Service',
        'Heizungsinstallateur',
        'Heizungsmonteur',
        'Hochbauzeichner',
        'ICT Client Supporter',
        'Incidunt vel expedi',
        'Industrielackierer',
        'Inhouse Senior Recruiter',
        'Instandhaltungstechniker',
        'Internal Applications Developer',
        'Internal Data Liaison',
        'Internal Functionality Analyst',
        'Junior Bereichsleiter',
        'Konstrukteur',
        'Kundenberater',
        'Kundendiensttechniker',
        'Kältesystem-Monteur',
        'Landmaschinenmechaniker',
        'Lebensmitteltechnologe',
        'Leiter',
        'Leitung',
        'Linienführer',
        'Logistiker',
        'Lüftungsinstallateur',
        'Magaziner',
        'Maler',
        'Mandatsleiter',
        'Market Manager',
        'Marketing Assistentin',
        'Marketing Manager',
        'Mechaniker',
        'Mechatroniker',
        'Metallbau-Konstrukteur',
        'Metallbauer',
        'Metallbaumonteur',
        'Metallbauschlosser',
        'Mitarbeiter Marketing / Vertrieb',
        'Mitarbeiter/ -in Büro und Ladenverkauf',
        'Mitarbeiterin Administration / Buchhaltung',
        'Mitarbeiterin Customer Service',
        'Mitarbeiterin Verkauf',
        'Montageleiter',
        'Monteur',
        'Nachwuchs-Disponent',
        'Näherin',
        'Operator',
        'Personalberaterin',
        'Pflegefachkraft',
        'Polymechaniker',
        'Process Engineer',
        'Projektleiter',
        'Qualitätsmanager',
        'Recyclist',
        'Regional Creative Liaison',
        'Sachbearbeiter',
        'Sanitärinstallateur',
        'Schaltanlagenmonteur',
        'Schreiner',
        'Senior Controller',
        'Serviceleiter',
        'Servicemonteur',
        'Servicetechniker',
        'Softwareingenieur',
        'Spengler',
        'Splitklima-Monteur',
        'Stahlbaumonteur',
        'Steuerberater',
        'Storemanager',
        'Technischer Sachbearbeiter',
        'Technischer Verkäufer',
        'Treuhänder',
        'Verkaufsberater Innendienst',
        'Verkaufsberaterin',
        'Wirtschaftsprüfer',
        'Zeichner',
        'Zimmermann'
    ];

    public skillAbbr = {
        // 'Analytische Fähigkeiten': 'AF',
        // 'Bewerbungsmanagement': 'BM',
        // 'CNC-Schleifen': 'CS',
        '3-Schicht-Arbeit': '3SA',
        '3D-CAD-Konstruktion': 'CAD',
        'ABACUS': 'AB',
        'Abacus': 'AB',
        'Abacus Kenntnisse': 'AB',
        'Abwechslungsreiche Arbeit': 'AA',
        'Accounting': 'AC',
        'Administration': 'AD',
        'Analytische Fähigkeiten': 'AF',
        'Analytisches Denken': 'AND',
        'Anlagen': 'A',
        'Anlagenführung': 'AF',
        'Anlagenwartung': 'AW',
        'Anpacken können': 'AK',
        'Anpassungsfähigkeit': 'APF',
        'Anstellungsbedingungen': 'ANB',
        'Applikationsmethoden in der industriellen Kunststoff-Produktion': 'AIK',
        'Arbeit mit unterstützungsbedürftigen Menschen': 'AUM',
        'Arbeitsbedingungen': 'AB',
        'Arbeitserfahrung': 'AE',
        'Arbeitsgeräte': 'AG',
        'Arbeitsgeschwindigkeit': 'AG',
        'Arbeitsorganisation': 'AO',
        'Arbeitsort': 'AO',
        'Arbeitsplatzorganisation': 'APO',
        'Arbeitsrecht': 'AR',
        'Arbeitssicherheit': 'AS',
        'Arbeitsvorbereitung': 'AV',
        'Arbeitszeitmanagement': 'AZM',
        'Attraktive Anstellungsbedingungen': 'AAB',
        'Auffassungsgabe': 'AG',
        'Auffassungsvermögen': 'AV',
        'Aufstiegsmöglichkeiten': 'AM',
        'Auftragsabwicklung': 'AA',
        'Ausbildung': 'A',
        'Ausbildung als Automatiker EFZ': 'AaA',
        'Ausbildung als Maler/in EFZ': 'AaM',
        'Ausbildung als Mechatroniker EFZ': 'AaM',
        'Ausbildung in Pflege oder FaGe': 'AiP',
        'Ausbildung zum Automobilmechatroniker': 'AzA',
        'Ausbildungsfähigkeit': 'AF',
        'Ausbildungssystem': 'AS',
        'Ausdauer': 'A',
        'Aussen- und Innendienst': 'AuI',
        'Automatikmontage': 'AM',
        'Automatisierungstechnik': 'AT',
        'Automobiltechnik': 'AMT',
        'Außendienst': 'AD',
        'BWL-Kenntnisse': 'BWL',
        'Bau': 'BAU',
        'Bauwesen': 'BW',
        'Belagsfertigung': 'BF',
        'Belastbarkeit': 'BEL',
        'Beobachtungsgenauigkeit': 'BG',
        'Beratung': 'B',
        'Bereitschaft für gelegentlichen Pikettdienst': 'BgP',
        'Bereitschaft zur Arbeit in Früh- oder Spätschichtmodellen': 'BFS',
        'Bereitschaft zur Mehrarbeit': 'BzM',
        'Bereitschaft zur Schichtarbeit': 'BzS',
        'Bereitschaft zur Überstundenarbeit': 'BzÜ',
        'Berufsausbildung': 'BA',
        'Berufsausbildung im Lebensmittelbereich': 'BiL',
        'Berufserfahrung': 'BE',
        'Berufserfahrung in der Detail- und Endmontage': 'BDE',
        'Berufserfahrung in der produzierenden Industrie': 'BpI',
        'Betreuung': 'BET',
        'Betriebsunterhalt': 'BU',
        'Betriebswirtschaftliche Fähigkeiten': 'BWF',
        'Betriebswirtschaftliche Kenntnisse': 'BWK',
        'Betriebswirtschaftliches Denken': 'BWD',
        'Betriebswirtschaftslehre': 'BWL',
        'Bewerbungsmanagement': 'BM',
        'Beziehungsmanagement': 'BZM',
        'Bilanzierung': 'BIL',
        'Branchenkenntnisse Heizung': 'BKH',
        'Buchhaltung': 'BH',
        'Bäckerei': 'BÄ',
        'CAD': 'CAD',
        'CAD-Kenntnisse': 'CAD',
        'CAD-Programme': 'CAD',
        'CNC-Fertigung': 'CNC',
        'CNC-Maschinen bedienen': 'CNC',
        'CNC-Programmierung': 'CNC',
        'CNC-Schleifen': 'CNC',
        'CNC-Steuerungen': 'CNC',
        'Chemie- und Pharmatechnologe': 'CuP',
        'Chemikant': 'CHE',
        'Chromstahl': 'CS',
        'Computerkenntnisse': 'CK',
        'Content-Erstellung': 'CE',
        'Controlling': 'C',
        'Datenanalyse': 'DA',
        'Datenbanken': 'DB',
        'Deutsch': 'DEU',
        'Deutschkenntnisse': 'DEU',
        'Deutschkenntnisse auf muttersprachlichem Niveau': 'DmN',
        'Deutschkenntnisse in Wort und Schrift': 'DWS',
        'Diagnose': 'DIA',
        'Diagnose von Fahrzeugproblemen': 'DvF',
        'Diagnosefähigkeit': 'DF',
        'Dienstleistungsorientierung': 'DLO',
        'Digitale Kompetenz': 'DK',
        'Digitale Tools': 'DT',
        'Diskretion': 'DIS',
        'Dispositionserfahrung': 'DPE',
        'Dokumentation von Patienteninformationen': 'DPI',
        'Drehen': 'D',
        'Flexibilität': 'F',
        'Kommunikationsfähigkeit': 'KF',
        'Kundenorientierung': 'KO',
        'Leitungsbereitschaft': 'LB',
        'Organisationsfähigkeit': 'OF',
        'Polymechanik': 'P',
        'Problemlösungsfähigkeit': 'PLF',
        'Qualitätsbewusstsein': 'QB',
        'Selbstständigkeit': 'SS',
        'Steuerungskenntnisse': 'SK',
        'Teamfähigkeit': 'TF',
        'Unternehmerisches Denken': 'UD',
    };
}