import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
    providedIn: 'root'
})
export class SystemService {

    public jobNames = [
        'Accounting',
        'Administration',
        'Anlageführer',
        'Anlagen- und Apparatebauer',
        'Anlagenführer',
        'Anwendungstechniker',
        'Assistentin Projektleitung',
        'Automatiker',
        'Automobilfachmann/ -Mechatroniker oder -Diagnostiker',
        'Bankschreiner',
        'Bauzeichner',
        'Berater Treuhand',
        'Betriebselektriker',
        'Betriebsmechaniker',
        'Blech-Schweisser',
        'CNC-Dreher',
        'Chemiker',
        'Corporate Response Liaison',
        'Disponent',
        'Dreher',
        'Einbaumaschinist',
        'Elektriker',
        'Elektromonteur',
        'Fachperson Betreuung',
        'Fachperson Gesundheit',
        'Fachperson Qualitätskontrolle',
        'Fenster-/Servicemonteur',
        'Florist',
        'Forward Integration Consultant',
        'HLKKS-Planer',
        'HR Fachperson',
        'HR-Generalistin',
        'Head of Customer Care Service',
        'Head of Service',
        'Heizungsinstallateur',
        'Heizungsmonteur',
        'Hochbauzeichner',
        'ICT Client Supporter',
        'Incidunt vel expedi',
        'Industrielackierer',
        'Inhouse Senior Recruiter',
        'Instandhaltungstechniker',
        'Internal Applications Developer',
        'Internal Data Liaison',
        'Internal Functionality Analyst',
        'Junior Bereichsleiter',
        'Konstrukteur',
        'Kundenberater',
        'Kundendiensttechniker',
        'Kältesystem-Monteur',
        'Landmaschinenmechaniker',
        'Lebensmitteltechnologe',
        'Leiter',
        'Leitung',
        'Linienführer',
        'Logistiker',
        'Lüftungsinstallateur',
        'Magaziner',
        'Maler',
        'Mandatsleiter',
        'Market Manager',
        'Marketing Assistentin',
        'Marketing Manager',
        'Mechaniker',
        'Mechatroniker',
        'Metallbau-Konstrukteur',
        'Metallbauer',
        'Metallbaumonteur',
        'Metallbauschlosser',
        'Mitarbeiter Marketing / Vertrieb',
        'Mitarbeiter/ -in Büro und Ladenverkauf',
        'Mitarbeiterin Administration / Buchhaltung',
        'Mitarbeiterin Customer Service',
        'Mitarbeiterin Verkauf',
        'Montageleiter',
        'Monteur',
        'Nachwuchs-Disponent',
        'Näherin',
        'Operator',
        'Personalberaterin',
        'Pflegefachkraft',
        'Polymechaniker',
        'Process Engineer',
        'Projektleiter',
        'Qualitätsmanager',
        'Recyclist',
        'Regional Creative Liaison',
        'Sachbearbeiter',
        'Sanitärinstallateur',
        'Schaltanlagenmonteur',
        'Schreiner',
        'Senior Controller',
        'Serviceleiter',
        'Servicemonteur',
        'Servicetechniker',
        'Softwareingenieur',
        'Spengler',
        'Splitklima-Monteur',
        'Stahlbaumonteur',
        'Steuerberater',
        'Storemanager',
        'Technischer Sachbearbeiter',
        'Technischer Verkäufer',
        'Treuhänder',
        'Verkaufsberater Innendienst',
        'Verkaufsberaterin',
        'Wirtschaftsprüfer',
        'Zeichner',
        'Zimmermann'
    ];


    public skillAbbr = {
        '3-Schicht-Arbeit': '3SA',
        '3D-CAD-Konstruktion': '3DK',
        'ABACUS': 'AB',
        'Abacus': 'AB',
        'Abacus Kenntnisse': 'AB',
        'Abwechslungsreiche Arbeit': 'AbA',
        'Accounting': 'AC',
        'Administration': 'AD',
        'Analytische Fähigkeiten': 'AnF',
        'Analytisches Denken': 'AND',
        'Anlagen': 'An',
        'Anlagenführung': 'AnF',
        'Anlagenwartung': 'AW',
        'Anpacken können': 'AK',
        'Anpassungsfähigkeit': 'APF',
        'Anstellungsbedingungen': 'ANB',
        'Applikationsmethoden in der industriellen Kunststoff-Produktion': 'AIK',
        'Arbeit mit unterstützungsbedürftigen Menschen': 'AUM',
        'Arbeitsbedingungen': 'ABed',
        'Arbeitserfahrung': 'AE',
        'Arbeitsgeräte': 'AGe',
        'Arbeitsgeschwindigkeit': 'AG',
        'Arbeitsorganisation': 'AOr',
        'Arbeitsort': 'AO',
        'Arbeitsplatzorganisation': 'APO',
        'Arbeitsrecht': 'AR',
        'Arbeitssicherheit': 'ASi',
        'Arbeitsvorbereitung': 'AV',
        'Arbeitszeitmanagement': 'AZM',
        'Attraktive Anstellungsbedingungen': 'AAB',
        'Auffassungsgabe': 'AuG',
        'Auffassungsvermögen': 'AuV',
        'Aufstiegsmöglichkeiten': 'AMö',
        'Auftragsabwicklung': 'AA',
        'Ausbildung': 'Aus',
        'Ausbildung als Automatiker EFZ': 'AAu',
        'Ausbildung als Maler/in EFZ': 'AMa',
        'Ausbildung als Mechatroniker EFZ': 'AMe',
        'Ausbildung in Pflege oder FaGe': 'AiP',
        'Ausbildung zum Automobilmechatroniker': 'AzA',
        'Ausbildungsfähigkeit': 'AF',
        'Ausbildungssystem': 'AS',
        'Ausdauer': 'A',
        'Aussen- und Innendienst': 'AuI',
        'Automatikmontage': 'AM',
        'Automatisierungstechnik': 'AT',
        'Automobiltechnik': 'AMT',
        'Außendienst': 'AuD',
        'BWL-Kenntnisse': 'BWL',
        'Bau': 'BAU',
        'Bauwesen': 'BW',
        'Belagsfertigung': 'BF',
        'Belastbarkeit': 'BEL',
        'Beobachtungsgenauigkeit': 'BG',
        'Beratung': 'B',
        'Bereitschaft für gelegentlichen Pikettdienst': 'BgP',
        'Bereitschaft zur Arbeit in Früh- oder Spätschichtmodellen': 'BFS',
        'Bereitschaft zur Mehrarbeit': 'BzM',
        'Bereitschaft zur Schichtarbeit': 'BzS',
        'Bereitschaft zur Überstundenarbeit': 'BzÜ',
        'Berufsausbildung': 'BA',
        'Berufsausbildung im Lebensmittelbereich': 'BiL',
        'Berufserfahrung': 'BE',
        'Berufserfahrung in der Detail- und Endmontage': 'BDE',
        'Berufserfahrung in der produzierenden Industrie': 'BpI',
        'Betreuung': 'BET',
        'Betriebsunterhalt': 'BU',
        'Betriebswirtschaftliche Fähigkeiten': 'BWF',
        'Betriebswirtschaftliche Kenntnisse': 'BWK',
        'Betriebswirtschaftliches Denken': 'BWD',
        'Betriebswirtschaftslehre': 'BWL',
        'Bewerbungsmanagement': 'BM',
        'Beziehungsmanagement': 'BZM',
        'Bilanzierung': 'BIL',
        'Branchenkenntnisse Heizung': 'BKH',
        'Buchhaltung': 'BH',
        'Bäckerei': 'BÄ',
        'CAD': 'CAD',
        'CAD-Kenntnisse': 'CADK',
        'CAD-Programme': 'CADP',
        'CNC-Fertigung': 'CNCF',
        'CNC-Maschinen bedienen': 'CNCM',
        'CNC-Programmierung': 'CNCP',
        'CNC-Schleifen': 'CNCS',
        'CNC-Steuerungen': 'CNC',
        'Chemie- und Pharmatechnologe': 'CuP',
        'Chemikant': 'CHE',
        'Chromstahl': 'CS',
        'Computerkenntnisse': 'CK',
        'Content-Erstellung': 'CE',
        'Controlling': 'Con',
        'Datenanalyse': 'DA',
        'Datenbanken': 'DB',
        'Deutsch': 'DEU',
        'Deutschkenntnisse': 'DEU',
        'Deutschkenntnisse auf muttersprachlichem Niveau': 'DmN',
        'Deutschkenntnisse in Wort und Schrift': 'DWS',
        'Diagnose': 'DIA',
        'Diagnose von Fahrzeugproblemen': 'DvF',
        'Diagnosefähigkeit': 'DF',
        'Dienstleistungsorientierung': 'DLO',
        'Digitale Kompetenz': 'DK',
        'Digitale Tools': 'DT',
        'Diskretion': 'DIS',
        'Dispositionserfahrung': 'DPE',
        'Dokumentation von Patienteninformationen': 'DPI',
        'Drehen': 'D',
        'Durchführung von zahnärztlichen Behandlungen': 'DzB',
        'Durchsetzungsvermögen': 'DV',
        'EDV-Kenntnisse': 'EDV',
        'ERP-System': 'ERP',
        'Effiziente Projektabwicklung': 'EPA',
        'Effizientes Arbeiten': 'EA',
        'Effizienz': 'Eff',
        'Eigeninitiative': 'EI',
        'Eigenständigkeit': 'ES',
        'Eigenverantwortliches Arbeiten': 'EiA',
        'Eigenverantwortung': 'EV',
        'Einarbeitung': 'EAr',
        'Einarbeitung neuer Mitarbeiter': 'EnM',
        'Einfühlungsvermögen': 'EVe',
        'Einkauf': 'Ein',
        'Einkaufsmanagement': 'EM',
        'Einsatzbereitschaft': 'EB',
        'Einsatzwillen': 'EW',
        'Elektrik': 'Ele',
        'Elektrische Systeme': 'ElS',
        'Elektroinstallation': 'EIn',
        'Elektromontage': 'ElM',
        'Elektronik': 'El',
        'Elektrotechnik': 'ElT',
        'Elternurlaub': 'EU',
        'Engagement': 'En',
        'Englischkenntnisse': 'ENG',
        'Entscheidungsfreudigkeit': 'EFr',
        'Entscheidungsfähigkeit': 'EF',
        'Entwicklung von Standards und Konzepten': 'ESK',
        'Entwicklungsmöglichkeiten': 'EMö',
        'Erfahrung': 'E',
        'Erfahrung als Projektleiter': 'EaP',
        'Erfahrung im Rechnungswesen': 'EiRw',
        'Erfahrung im Reinigungsbereich': 'EiR',
        'Erfahrung im Unterhalt von Produktionsanlagen': 'EUP',
        'Erfahrung in Matrixstrukturen': 'EiM',
        'Erfahrung in Service Auftragsabwicklung': 'ESA',
        'Erfahrung in der Lebensmittelbranche': 'ELB',
        'Exakte Arbeitsweise': 'EAW',
        'Exaktes Arbeiten': 'ExA',
        'Exaktheit': 'Ex',
        'Expertendiplom im Bereich Steuern': 'EBS',
        'Expertendiplom im Treuhand': 'EiT',
        'Expertendiplom in Wirtschaftsprüfung': 'EiW',
        'Expertise': 'Exp',
        'Fachausweis Treuhand': 'FT',
        'Fachbewilligung für den Umgang mit Kältemitteln': 'FUK',
        'Fachinstruktionen und Wissensvermittlung': 'FWV',
        'Fachliche Kompetenz': 'FK',
        'Fachwissen': 'FW',
        'Fachwissen im Energiesektor': 'FiE',
        'Fachwissen in der Werkstatt': 'FWe',
        'Fahrer': 'F',
        'Fahrerfahrung': 'FEr',
        'Fahrerlaubnis CE': 'FCE',
        'Fahrerlaubnis Klasse B': 'FB',
        'Fahrzeugführung': 'FF',
        'Fahrzeugreparatur': 'FR',
        'Fahrzeugtechnik': 'FTe',
        'Fahrzeugwartung': 'FaW',
        'Fanuc': 'Fan',
        'Farb- und Materialkenntnisse': 'FuM',
        'Fassadenbau': 'FBa',
        'Feinmotorik': 'Fei',
        'Fenster- und Türkenntnisse': 'FuT',
        'Finanzanalyse': 'FiA',
        'Finanzbuchhaltung': 'FiB',
        'Finanzplanung': 'FiP',
        'Finanzwesen': 'FiW',
        'Firmenwagen': 'FWa',
        'Fitness': 'Fit',
        'Flache Hierarchien': 'FHi',
        'Flexibilität': 'Flx',
        'Flurförderfahrzeuge': 'FFF',
        'Fortgeschrittene Anstellungsbedingungen': 'FAb',
        'Fortschrittlichkeit': 'For',
        'Französischkenntnisse': 'FrK',
        'Freundliches Auftreten': 'FrA',
        'Fräsen': 'Frä',
        'Führerausweis Kat. BE': 'FBE',
        'Führerausweis Kategorie B': 'FB',
        'Führerschein': 'FS',
        'Führerschein B': 'FB',
        'Führerschein Kat. B/BE': 'FBBE',
        'Führerschein Klasse B': 'FB',
        'Führung': 'Fü',
        'Führung von Auszubildenden': 'FüA',
        'Führungserfahrung': 'FüE',
        'Führungskompetenz': 'FüK',
        'Führungskompetenzen': 'FüK',
        'Führungsqualitäten': 'FüQ',
        'Genauigkeit': 'Gen',
        'Geografische Kenntnisse': 'Geo',
        'Geographiekenntnisse': 'Geo',
        'Geschicklichkeit': 'Ges',
        'Geschäftsbeziehung': 'GeB',
        'Gesunde Arbeitseinstellung': 'GeA',
        'Gesundheit und Ernährung': 'GuE',
        'Getränkeindustrie': 'GeI',
        'Grundausbildung im Bereich': 'GiB',
        'Grundausbildung im Holzgewerbe': 'GiH',
        'Gute Verkehrsanbindung': 'GVA',
        'HR': 'HR',
        'Hallenbau': 'HaB',
        'Hands-on-Mentalität': 'HoM',
        'Handwerkliche Ausbildung': 'HaA',
        'Handwerkliche Fertigkeiten': 'HaFe',
        'Handwerkliche Fähigkeiten': 'HaFä',
        'Handwerkliches Geschick': 'HaG',
        'Haushaltsgeräte': 'HG',
        'Heizungsinstallation': 'HeI',
        'Heizungstechnik': 'HeT',
        'Hochbau und Innenausbau': 'HuI',
        'Hochbauzeichnung': 'Hbz',
        'Holzbearbeitung': 'HB',
        'Homeoffice': 'HO',
        'Hubwagenfahren': 'Hub',
        'Hygiene': 'HY',
        'Hygienevorschriften': 'HYV',
        'Hygienevorschriften einhalten': 'HYVe',
        'Höhentauglichkeit': 'HöT',
        'ICT-Support': 'ICT',
        'ISO-Code': 'ISO',
        'IT': 'IT',
        'IT-Affinität': 'ITA',
        'IT-Kenntnisse': 'ITK',
        'IT-Projektgeschäft': 'ITP',
        'Inbetriebnahme': 'Inb',
        'Industrieelektronik': 'InE',
        'Industrielle Fertigung': 'InF',
        'Industrielle Kunststoffspritzgusstechnik': 'InKS',
        'Infoniqa one 50': 'Io50',
        'Initiative': 'Ini',
        'Innendienst': 'ID',
        'Innovation': 'In',
        'Innovationsfähigkeit': 'IFä',
        'Instrumentenaufbereitung': 'IA',
        'Interdisziplinäre Zusammenarbeit': 'IdZ',
        'Interesse am Massivholzbau': 'IaM',
        'Interkulturelle Kompetenz': 'IkK',
        'Internationale Erfahrung': 'ItE',
        'Internationale Kompetenz': 'ItK',
        'Internationale Zusammenarbeit': 'ItZ',
        'Internationales Umfeld': 'ItU',
        'Italienischkenntnisse': 'I',
        'KMU': 'KMU',
        'KMU-Beratung': 'KMUB',
        'Karriereentwicklung': 'KE',
        'Kaufmännische Ausbildung': 'KaA',
        'Kaufmännische Grundausbildung': 'KaG',
        'Kaufmännische Kenntnisse': 'KaK',
        'Kaufmännische Weiterbildung': 'KaW',
        'Kaufmännischer Abschluss': 'KaAb',
        'Kaufmännisches Verständnis': 'KaV',
        'Kaufmännisches Wissen': 'KaWi',
        'Kenntnisse der Service-Auftragsabwicklung': 'KSA',
        'Kenntnisse im Transportrecht': 'KiT',
        'Kenntnisse in Automatisierungstechnik': 'KiA',
        'Kenntnisse in Excel und Business Intelligence': 'KEBI',
        'Kenntnisse in MS Office, SAP und Datenanalysetools': 'KOSD',
        'Kenntnisse in Microsoft Office und ERP-Systemen': 'KOE',
        'Kenntnisse in Service-Auftragsabwicklung': 'KiSA',
        'Kenntnisse in Swiss GAAP': 'KiSG',
        'Kenntnisse in elektrischen Baugruppen': 'KieB',
        'Kenntnisse in elektronischen Baugruppen': 'KieB',
        'Kenntnisse in mechanischen Baugruppen': 'KimB',
        'Know-how-Vertiefung': 'KhV',
        'Kochen': 'K',
        'Kollegiales Arbeitsklima': 'KoA',
        'Kollegialität': 'Ko',
        'Kommunikation': 'Kom',
        'Kommunikation mit Kollegen': 'KoK',
        'Kommunikation mit Kunden': 'KomK',
        'Kommunikation mit Patienten': 'KoP',
        'Kommunikationsfähigkeit': 'KF',
        'Kommunikationsfähigkeiten': 'KF',
        'Komplexitätsbewältigung': 'KBe',
        'Konfliktmanagement': 'KM',
        'Konstruktion': 'Kon',
        'Konstruktivität': 'Kov',
        'Kooperationsfähigkeit': 'Koo',
        'Kostenrechnung': 'KoR',
        'Kreativität': 'Kre',
        'Kultur': 'Kul',
        'Kundenberatung': 'KBa',
        'Kundenbetreuung': 'KBe',
        'Kundendienst': 'KDi',
        'Kundenkontakt': 'KKo',
        'Kundenorientierung': 'KOr',
        'Kundenspezifische Lösungen': 'KsL',
        'Kunststoffspritzgiessproduktionsprozesse': 'Kspp',
        'Kunststoffspritzgussfragen': 'Ksf',
        'Kunststoffspritzgusstechnik': 'Kst',
        'Kunststofftechnologe-EFZ': 'KtE',
        'Kältemontage': 'KäM',
        'Kältesystemmontage': 'KäS',
        'Kältetechnik': 'KäT',
        'Körperliche Arbeit': 'KöA',
        'Körperliche Belastbarkeit': 'KöB',
        'Körperliche Fitness': 'KöF',
        'Laborant': 'Lab',
        'Lackiertechnik': 'LaT',
        'Lagerhaltung': 'LH',
        'Langfristige Karriereplanung': 'LKp',
        'Langfristige Planung': 'LP',
        'Leadership': 'Lea',
        'Lebensmittelhygiene': 'LeH',
        'Lebensmittelindustrie': 'LeI',
        'Lebensmittelproduktion': 'LeP',
        'Lebensmitteltechnologie': 'LeT',
        'Lederbearbeitung': 'LBe',
        'Lehre': 'L',
        'Leichtbau': 'LB',
        'Leistungsorientierung': 'LO',
        'Leitungsbau': 'LeB',
        'Leitungsbereitschaft': 'LBs',
        'Lernbereitschaft': 'LBer',
        'Lesen und Interpretieren von technischen Zeichnungen': 'LITZ',
        'Lieferantenmanagement': 'LiM',
        'Logistik': 'Log',
        'Lohnabrechnung': 'LAb',
        'Lohnbuchhaltung': 'Lbh',
        'Lohnwesen': 'LW',
        'Loyalität': 'Loy',
        'Lösungsfindung': 'LöF',
        'Lösungsorientiertes Denken': 'LöD',
        'Lösungsorientierung': 'LöÖ',
        'MS Office': 'MS',
        'MS Office-Kenntnisse': 'MSK',
        'MS-Dynamics NAV': 'MSN',
        'MS-Office': 'MS',
        'MS-Office Anwenderkenntnisse': 'MSAk',
        'MS-Office Anwendungen': 'MSA',
        'MS-Office Kenntnisse': 'MSK',
        'MS-Office-Kenntnisse': 'MSK',
        'Malerarbeiten ausführen': 'MaA',
        'Managementfähigkeiten': 'MmF',
        'Marketing': 'Ma',
        'Marketingmanagement': 'MaM',
        'Marktkenntnisse': 'Mkt',
        'Maschinenbau': 'Mas',
        'Maschinenbedienung': 'MaB',
        'MasterCAM-Programmierung': 'MCP',
        'Materialkenntnisse': 'MK',
        'Mechanik': 'Me',
        'Mechanische Fertigung': 'MeF',
        'Mechanische Fähigkeiten': 'MeFä',
        'Mechatronik': 'Mec',
        'Metallbau': 'Mb',
        'Metallbaukonstruktion': 'MbK',
        'Metallbearbeitung': 'MBe',
        'Metallverarbeitung': 'MVe',
        'Milchtechnologie': 'MiT',
        'Mitarbeiterführung': 'MiF',
        'Mitarbeiterkonditionen': 'MiK',
        'Mitarbeiterrabatte': 'MiR',
        'Mitsprache bei Arbeitszeit- und Feriengestaltung': 'MAF',
        'Mobilität': 'Mo',
        'Moderne Büroausstattung': 'MoB',
        'Montage': 'Mon',
        'Motivation': 'Mot',
        'Muffenmonteur Kunststoffmantelrohre': 'MmK',
        'Multitasking-Fähigkeiten': 'MTF',
        'Netzwerkaufbau': 'NA',
        'Netzwerktechnik': 'NT',
        'Offenheit': 'Off',
        'Office-Programme': 'OP',
        'Optimierung von Geschäftsprozessen': 'OvG',
        'Ordnung und Sauberkeit': 'OuS',
        'Organisation': 'Org',
        'Organisationsfähigkeit': 'OrF',
        'Organisationstalent': 'OrT',
        'Ortskenntnisse': 'OK',
        'Outdoor-Aktivitäten': 'OA',
        'PC-Kenntnisse': 'PC',
        'Parkplatzmanagement': 'PpM',
        'Patientenbetreuung': 'PBe',
        'Pensionskassenmanagement': 'PKM',
        'Periphere Systeme': 'PSy',
        'Personaladministration': 'PeA',
        'Personalentwicklung': 'PeE',
        'Personalmanagement': 'PeM',
        'Personalwesen': 'PeW',
        'Pflege': 'Pf',
        'Pflege und Betreuung': 'PfB',
        'Pikettdienst': 'PD',
        'Planlesen': 'PL',
        'Planung': 'Pla',
        'Poly- oder Landmaschinenmechanik': 'PoL',
        'Polymechanik': 'Pol',
        'Praktische Erfahrung im Bereich Kältetechnik': 'PEK',
        'Praxiserfahrung in HR/Payroll': 'PHR',
        'Praxisorientierte Berufserfahrung in der Treuhand': 'PBT',
        'Priorisierungsfähigkeit': 'PFä',
        'Proaktives Handeln': 'PrH',
        'Problemanalyse': 'PrA',
        'Problemlösung': 'PrL',
        'Problemlösungsfähigkeit': 'PLF',
        'Problemlösungskompetenz': 'PLK',
        'Produktionsförderung': 'PFö',
        'Produktionsplanung': 'PPl',
        'Produktionsprozesse': 'PR',
        'Produktionsüberwachung': 'PÜ',
        'Programmierung': 'Pro',
        'Projektmanagement': 'PM',
        'Prozessleitsysteme: Simatic PCS 7, Valmet, TIA-Portal, S7': 'PLS',
        'Prozessmanagement': 'PrM',
        'Prozessoptimierung': 'PrO',
        'Präzise Arbeitsweise': 'PäA',
        'Präzises, strukturiertes und eigenständiges Arbeiten unter Einhaltung aller Sicherheitsvorschriften': 'PAES',
        'Präzision': 'Prä',
        'Präzisionsarbeit': 'PAr',
        'Qualitätsanspruch': 'QA',
        'Qualitätsbewusstsein': 'QB',
        'Qualitätskontrolle': 'QK',
        'Qualitätsmanagement': 'QM',
        'Qualitätssicherung': 'QS',
        'RAB Zulassung als Revisionsexperte': 'RAB',
        'Reaktionsfähigkeit': 'RF',
        'Rechnungswesen': 'RW',
        'Recruiting': 'Rec',
        'Regionale Kenntnisse': 'RK',
        'Reparatur': 'Rep',
        'Reparatur von Kälteanlagen': 'ReK',
        'Risikomanagement': 'RM',
        'Robustheit': 'Ro',
        'Räumliches Vorstellungsvermögen': 'RV',
        'SAP': 'SAP',
        'SAP Business One Kenntnisse': 'SBO',
        'SAP-Kenntnisse': 'SAP',
        'SPS Programmierung': 'SPS',
        'SPS-Programmierung': 'SPS',
        'Sandstrahltechnik': 'SST',
        'Sanitärinstallation': 'SI',
        'Sauberes Arbeiten': 'SAr',
        'Schaltanlagenmontage': 'SAM',
        'Schichtarbeit': 'ScA',
        'Schnelle Auffassungsgabe': 'SAg',
        'Schnelligkeit': 'Sch',
        'Schreiner': 'Sr',
        'Schreinerarbeiten durchführen': 'SrA',
        'Schreinerausbildung EFZ': 'SrE',
        'Schweissen': 'Swe',
        'Selbstdisziplin': 'SeD',
        'Selbstständige Arbeitsweise': 'SeAw',
        'Selbstständiges Arbeiten': 'SeA',
        'Selbstständigkeit': 'Ses',
        'Selbständige Arbeitsweise': 'SeAw',
        'Selbständiges Arbeiten': 'SeA',
        'Selbständigkeit': 'Se',
        'Service- und Dienstleistungsorientierung': 'SuD',
        'Service-Auftragsabwicklung': 'SAu',
        'Servicebereich': 'SB',
        'Sicherheitsvorschriften': 'SV',
        'Social-Media-Management': 'SMM',
        'Softwareentwicklung': 'SE',
        'Sorgfalt': 'Sor',
        'Sorgfältige Arbeitsweise': 'SoA',
        'Souveränes Auftreten': 'SuA',
        'Sozialkompetenz': 'SoK',
        'Sozialleistungen': 'SoL',
        'Sozialversicherung': 'SoV',
        'Speditionskenntnisse': 'SpK',
        'Speditivität': 'Spe',
        'Sport': 'Spo',
        'Sprachkenntnisse': 'SK',
        'Sprachkenntnisse (Deutsch und Französisch)': 'SDF',
        'Staplerfahren': 'Stf',
        'Steuerrecht': 'Ste',
        'Steuerungskenntnisse': 'StK',
        'Strassenbau': 'StB',
        'Stressresistenz': 'StR',
        'Strukturierte Arbeitsweise': 'StAw',
        'Strukturiertes Arbeiten': 'StA',
        'Strukturierung': 'Str',
        'Störungsbehebung': 'Stö',
        'Swiss GAAP': 'SGA',
        'Systematische Arbeitsweise': 'SyA',
        'Teamarbeit': 'TA',
        'Teamfähigkeit': 'TF',
        'Teamführung': 'TFü',
        'Teamorientierung': 'TO',
        'Teamplayerfähigkeiten': 'TPF',
        'Technische Ausbildung': 'TeA',
        'Technische Grundausbildung': 'TeG',
        'Technische Kenntnisse': 'TeK',
        'Technisches Grundverständnis': 'TeGv',
        'Technisches Verständnis': 'TeV',
        'Terminmanagement': 'TM',
        'Tiefbau': 'TB',
        'Transportdisposition': 'TD',
        'Treuhand': 'TH',
        'Treuhandwesen': 'THW',
        'Umgangsformen': 'UF',
        'Umsichtigkeit': 'UK',
        'Unternehmergeist': 'UG',
        'Unternehmerisches Denken': 'UD',
        'Unternehmertum': 'U',
        'Urlaubs- und Weihnachtsgeld': 'UuW',
        'Verantwortungsbewusstsein': 'VeB',
        'Verantwortungsvolle Position': 'VeP',
        'Verhandlungsfähigkeiten': 'VeF',
        'Verhandlungsführung': 'VeFü',
        'Verhandlungsgeschick': 'VeG',
        'Verkauf': 'V',
        'Verkauf Innendienst': 'VI',
        'Verkaufsfähigkeiten': 'VF',
        'Verkaufsförderung': 'VFö',
        'Verkaufsinnendienst': 'Vi',
        'Verkaufstechniken': 'VT',
        'Vernetztes Denken': 'VN',
        'Vertrieb': 'Ve',
        'Vertriebsinnendienst': 'VeI',
        'Verwaltungsaufgaben': 'VeA',
        'Vielseitigkeit': 'Vsk',
        'Vorbereitung von Behandlungsräumen': 'VvB',
        'Vorstellungsvermögen': 'VV',
        'Wartung': 'W',
        'Wartung und Reparatur': 'WR',
        'Wartung und Reparatur von Maschinen': 'WRM',
        'Wartung und Reparatur von Maschinen und Anlagen': 'WRMA',
        'Wartung von Kälteanlagen': 'WK',
        'Wartung von Produktionsanlagen': 'WP',
        'Weiterbildung': 'We',
        'Weiterbildung im Bereich Rechnungswesen': 'WBR',
        'Weiterbildungsbereitschaft': 'WBB',
        'Werkzeugbedienung': 'WeB',
        'Wettbewerbsfähige Gehälter': 'WeG',
        'Wetterfestigkeit': 'WF',
        'Wirtschaftsprüfung': 'WiP',
        'Zeichnen': 'Ze',
        'Zeitmanagement': 'ZM',
        'Zerspanende Mechanik': 'ZeM',
        'Zielorientierte Arbeitsweise': 'ZiA',
        'Zielorientierung': 'ZiO',
        'Zimmermann': 'Zim',
        'Zusammenarbeit': 'Zus',
        'Zusammenarbeit mit anderen Handwerkern': 'ZaH',
        'Zuverlässigkeit': 'Zuv',
        'betriebliche Altersvorsorge': 'bAv',
        'Überstundenausgleich': 'ÜA'
    };
}